name: "le_test"
type: "php:7.0"
disk: "256"
build:
  flavor: none
web:
  locations:
    '/':
      root: 'web'
      passthru: '/index.php'
      index:
        - index.php
      expires: -1
      scripts: true
      allow: true
      
